/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppListing {
    }
    interface AppRoot {
    }
    interface RepositoryContributorList {
        "contributorList": Array<any>;
    }
    interface RepositoryDetail {
        "repoInfo": any;
    }
}
declare global {
    interface HTMLAppListingElement extends Components.AppListing, HTMLStencilElement {
    }
    var HTMLAppListingElement: {
        prototype: HTMLAppListingElement;
        new (): HTMLAppListingElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLRepositoryContributorListElement extends Components.RepositoryContributorList, HTMLStencilElement {
    }
    var HTMLRepositoryContributorListElement: {
        prototype: HTMLRepositoryContributorListElement;
        new (): HTMLRepositoryContributorListElement;
    };
    interface HTMLRepositoryDetailElement extends Components.RepositoryDetail, HTMLStencilElement {
    }
    var HTMLRepositoryDetailElement: {
        prototype: HTMLRepositoryDetailElement;
        new (): HTMLRepositoryDetailElement;
    };
    interface HTMLElementTagNameMap {
        "app-listing": HTMLAppListingElement;
        "app-root": HTMLAppRootElement;
        "repository-contributor-list": HTMLRepositoryContributorListElement;
        "repository-detail": HTMLRepositoryDetailElement;
    }
}
declare namespace LocalJSX {
    interface AppListing {
    }
    interface AppRoot {
    }
    interface RepositoryContributorList {
        "contributorList"?: Array<any>;
    }
    interface RepositoryDetail {
        "repoInfo"?: any;
    }
    interface IntrinsicElements {
        "app-listing": AppListing;
        "app-root": AppRoot;
        "repository-contributor-list": RepositoryContributorList;
        "repository-detail": RepositoryDetail;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-listing": LocalJSX.AppListing & JSXBase.HTMLAttributes<HTMLAppListingElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "repository-contributor-list": LocalJSX.RepositoryContributorList & JSXBase.HTMLAttributes<HTMLRepositoryContributorListElement>;
            "repository-detail": LocalJSX.RepositoryDetail & JSXBase.HTMLAttributes<HTMLRepositoryDetailElement>;
        }
    }
}
